### ISSUE TITLE
Question: Normal that tapping a roku channel thumbnail goes to the channel's store page?

### ISSUE THREAD

**Issue by megalithic** [imbrianj/switchBoard#49]
Brian,

Awesome job on this app. You've put in a tremendous amount of work. I've been going through the code to get familiar with everything you've done.

Once thing I was reading up on is Roku's external control API to see if it is normal/correct for the launch endpoint to take you to the app's channel page, or to actually open that channel. I've not seen much on their API docs page telling me one way or the other. Presently it just takes me to the channel's page in the channel store and I have to then execute on the 'open channel' link. Just wanted to confirm this is expected behavior.

I saw they are, or have already opened up the ability to pass parameters along as a POST. Not sure if this will change anything. I'll tinker in postman or regular old curl to see if i can get something to work in the meantime.

Thanks!

**Comment by imbrianj** [comment]
Hi Seth,

Thank you for the kind words.

Yes, currently, it just takes you to the app page.  The path is simply
"launch/11?ContentID=[your content]" found here:
https://github.com/imbrianj/switchBoard/blob/master/devices/roku/controller.js#L112

To my knowledge, this was the only method to easily access a given
channel on Roku.  If you can refer me to docs that have a better
method, I can happily update it.  I'll look around, myself as well.

Alternatively, it would be trivial to have Switchboard execute a macro
to access any of your channels with:

?roku=launch-28,Select

There's a .3s delay between each command by default.  You can increase
this with:

?roku=launch-28,Sleep,Sleep,Select

If you have any questions, please feel free to reach out.  I'm always
idling on freenode here:
http://webchat.freenode.net/?channels=#%23switchboard

Thanks,


Brian
